package modelo;
// Generated 02/07/2017 21:48:04 by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private ProductoId id;
     private String nombre;

    public Producto() {
    }

	
    public Producto(ProductoId id) {
        this.id = id;
    }
    public Producto(ProductoId id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public ProductoId getId() {
        return this.id;
    }
    
    public void setId(ProductoId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


