package modelo;
// Generated 02/07/2017 21:48:04 by Hibernate Tools 4.3.1



/**
 * ProductoId generated by hbm2java
 */
public class ProductoId  implements java.io.Serializable {


     private int id;
     private int codigo;

    public ProductoId() {
    }

    public ProductoId(int id, int codigo) {
       this.id = id;
       this.codigo = codigo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductoId) ) return false;
		 ProductoId castOther = ( ProductoId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getCodigo()==castOther.getCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getCodigo();
         return result;
   }   


}


