package Modelo;
// Generated 02/02/2018 22:50:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Entradastock generated by hbm2java
 */
public class Entradastock  implements java.io.Serializable {


     private int id;
     private Proveedor proveedor;
     private Date fechaHora;
     private BigDecimal importe;
     private Set itemEntradastocks = new HashSet(0);

    public Entradastock() {
    }

	
    public Entradastock(int id, Proveedor proveedor, Date fechaHora) {
        this.id = id;
        this.proveedor = proveedor;
        this.fechaHora = fechaHora;
    }
    public Entradastock(int id, Proveedor proveedor, Date fechaHora, BigDecimal importe, Set itemEntradastocks) {
       this.id = id;
       this.proveedor = proveedor;
       this.fechaHora = fechaHora;
       this.importe = importe;
       this.itemEntradastocks = itemEntradastocks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    public Set getItemEntradastocks() {
        return this.itemEntradastocks;
    }
    
    public void setItemEntradastocks(Set itemEntradastocks) {
        this.itemEntradastocks = itemEntradastocks;
    }




}


