package Modelo;
// Generated 02/02/2018 22:50:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * EntradaSalida generated by hbm2java
 */
public class EntradaSalida  implements java.io.Serializable {


     private int id;
     private Turno turno;
     private String nombre;
     private String descripcion;
     private int cantProd;
     private BigDecimal monto;
     private boolean tipo;
     private Date hora;

    public EntradaSalida() {
    }

	
    public EntradaSalida(int id, Turno turno, String nombre, int cantProd, BigDecimal monto, boolean tipo, Date hora) {
        this.id = id;
        this.turno = turno;
        this.nombre = nombre;
        this.cantProd = cantProd;
        this.monto = monto;
        this.tipo = tipo;
        this.hora = hora;
    }
    public EntradaSalida(int id, Turno turno, String nombre, String descripcion, int cantProd, BigDecimal monto, boolean tipo, Date hora) {
       this.id = id;
       this.turno = turno;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.cantProd = cantProd;
       this.monto = monto;
       this.tipo = tipo;
       this.hora = hora;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getCantProd() {
        return this.cantProd;
    }
    
    public void setCantProd(int cantProd) {
        this.cantProd = cantProd;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public boolean isTipo() {
        return this.tipo;
    }
    
    public void setTipo(boolean tipo) {
        this.tipo = tipo;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


