package Modelo;
// Generated 07/09/2017 19:19:57 by Hibernate Tools 4.3.1



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private int id;
     private Pedido pedido;
     private Turno turno;

    public Historial() {
    }

	
    public Historial(int id) {
        this.id = id;
    }
    public Historial(int id, Pedido pedido, Turno turno) {
       this.id = id;
       this.pedido = pedido;
       this.turno = turno;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }




}


