package Modelo;
// Generated 07/09/2017 19:19:57 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ItemPedido generated by hbm2java
 */
public class ItemPedido  implements java.io.Serializable {


     private int id;
     private Producto producto;
     //private Serializable producto;
     private BigDecimal cantidad;
     //private Set pedidos = new HashSet(0);

    public ItemPedido() {
    }

	
    public ItemPedido(int id, Producto producto, BigDecimal cantidad) {
        this.id = id;
        this.producto = producto;
        this.cantidad = cantidad;
    }
    public ItemPedido(int id, Producto producto, BigDecimal cantidad, Set pedidos) {
       this.id = id;
       this.producto = producto;
       this.cantidad = cantidad;
       //this.pedidos = pedidos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    /*public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }*/




}


