package Modelo;
// Generated 02/02/2018 22:50:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ItemEntradastock generated by hbm2java
 */
public class ItemEntradastock  implements java.io.Serializable {


     private int id;
     private Entradastock entradastock;
     private Producto producto;
     private int cantidad;
     private BigDecimal precioCostoItem;

    public ItemEntradastock() {
    }

	
    public ItemEntradastock(int id, Entradastock entradastock, Producto producto, int cantidad) {
        this.id = id;
        this.entradastock = entradastock;
        this.producto = producto;
        this.cantidad = cantidad;
    }
    public ItemEntradastock(int id, Entradastock entradastock, Producto producto, int cantidad, BigDecimal precioCostoItem) {
       this.id = id;
       this.entradastock = entradastock;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precioCostoItem = precioCostoItem;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Entradastock getEntradastock() {
        return this.entradastock;
    }
    
    public void setEntradastock(Entradastock entradastock) {
        this.entradastock = entradastock;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioCostoItem() {
        return this.precioCostoItem;
    }
    
    public void setPrecioCostoItem(BigDecimal precioCostoItem) {
        this.precioCostoItem = precioCostoItem;
    }




}


