package Modelo;
// Generated 02/02/2018 22:50:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ItemVenta generated by hbm2java
 */
public class ItemVenta  implements java.io.Serializable {


     private int id;
     private Producto producto;
     private Turno turno;
     private int cantidad;
     private BigDecimal monto;
     private Date hora;

    public ItemVenta() {
    }

    public ItemVenta(int id, Producto producto, Turno turno, int cantidad, BigDecimal monto, Date hora) {
       this.id = id;
       this.producto = producto;
       this.turno = turno;
       this.cantidad = cantidad;
       this.monto = monto;
       this.hora = hora;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


