package Modelo;
// Generated 02/02/2018 22:50:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private String codigo;
     private String descripcion;
     private BigDecimal precioCosto;
     private BigDecimal precioVenta;
     private BigDecimal precioVentaXKilo;
     private int stock;
     private Integer stockMinimo;
     private Integer pesoEnvase;
     private Boolean estado;
     private Boolean suspendido;
     private Boolean oferta;
     private Boolean porPeso;
     private Set proveedors = new HashSet(0);
     private Set itemVentas = new HashSet(0);
     private Set itemPedidos = new HashSet(0);
     private Set itemEntradastocks = new HashSet(0);
     private Set itemImprimirs = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int idProducto, String codigo, String descripcion, int stock) {
        this.idProducto = idProducto;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.stock = stock;
    }
    public Producto(int idProducto, String codigo, String descripcion, BigDecimal precioCosto, BigDecimal precioVenta, BigDecimal precioVentaXKilo, int stock, Integer stockMinimo, Integer pesoEnvase, Boolean estado, Boolean suspendido, Boolean oferta, Boolean porPeso, Set proveedors, Set itemVentas, Set itemPedidos, Set itemEntradastocks, Set itemImprimirs) {
       this.idProducto = idProducto;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.precioCosto = precioCosto;
       this.precioVenta = precioVenta;
       this.precioVentaXKilo = precioVentaXKilo;
       this.stock = stock;
       this.stockMinimo = stockMinimo;
       this.pesoEnvase = pesoEnvase;
       this.estado = estado;
       this.suspendido = suspendido;
       this.oferta = oferta;
       this.porPeso = porPeso;
       this.proveedors = proveedors;
       this.itemVentas = itemVentas;
       this.itemPedidos = itemPedidos;
       this.itemEntradastocks = itemEntradastocks;
       this.itemImprimirs = itemImprimirs;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecioCosto() {
        return this.precioCosto;
    }
    
    public void setPrecioCosto(BigDecimal precioCosto) {
        this.precioCosto = precioCosto;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public BigDecimal getPrecioVentaXKilo() {
        return this.precioVentaXKilo;
    }
    
    public void setPrecioVentaXKilo(BigDecimal precioVentaXKilo) {
        this.precioVentaXKilo = precioVentaXKilo;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Integer getStockMinimo() {
        return this.stockMinimo;
    }
    
    public void setStockMinimo(Integer stockMinimo) {
        this.stockMinimo = stockMinimo;
    }
    public Integer getPesoEnvase() {
        return this.pesoEnvase;
    }
    
    public void setPesoEnvase(Integer pesoEnvase) {
        this.pesoEnvase = pesoEnvase;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Boolean getSuspendido() {
        return this.suspendido;
    }
    
    public void setSuspendido(Boolean suspendido) {
        this.suspendido = suspendido;
    }
    public Boolean getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Boolean oferta) {
        this.oferta = oferta;
    }
    public Boolean getPorPeso() {
        return this.porPeso;
    }
    
    public void setPorPeso(Boolean porPeso) {
        this.porPeso = porPeso;
    }
    public Set getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set proveedors) {
        this.proveedors = proveedors;
    }
    public Set getItemVentas() {
        return this.itemVentas;
    }
    
    public void setItemVentas(Set itemVentas) {
        this.itemVentas = itemVentas;
    }
    public Set getItemPedidos() {
        return this.itemPedidos;
    }
    
    public void setItemPedidos(Set itemPedidos) {
        this.itemPedidos = itemPedidos;
    }
    public Set getItemEntradastocks() {
        return this.itemEntradastocks;
    }
    
    public void setItemEntradastocks(Set itemEntradastocks) {
        this.itemEntradastocks = itemEntradastocks;
    }
    public Set getItemImprimirs() {
        return this.itemImprimirs;
    }
    
    public void setItemImprimirs(Set itemImprimirs) {
        this.itemImprimirs = itemImprimirs;
    }




}


