package Modelo;
// Generated 07/09/2017 19:19:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int id;
     private String codigo;
     private String descripcion;
     private BigDecimal precioXKilo;
     private BigDecimal precioXUnidad;
     private BigDecimal stock;
     private BigDecimal stockMinimo;
     private BigDecimal pesoEnvase;
     private boolean estado;

    public Producto() {
    }

	
    public Producto(int id, String codigo, String descripcion, BigDecimal precioXKilo, BigDecimal precioXUnidad, BigDecimal stock, BigDecimal stockMinimo) {
        this.id = id;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.precioXKilo = precioXKilo;
        this.precioXUnidad = precioXUnidad;
        this.stock = stock;
        this.stockMinimo = stockMinimo;
    }
    public Producto(int id, String codigo, String descripcion, BigDecimal precioXKilo, BigDecimal precioXUnidad, BigDecimal stock, BigDecimal stockMinimo, BigDecimal pesoEnvase) {
       this.id = id;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.precioXKilo = precioXKilo;
       this.precioXUnidad = precioXUnidad;
       this.stock = stock;
       this.stockMinimo = stockMinimo;
       this.pesoEnvase = pesoEnvase;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecioXKilo() {
        return this.precioXKilo;
    }
    
    public void setPrecioXKilo(BigDecimal precioXKilo) {
        this.precioXKilo = precioXKilo;
    }
    public BigDecimal getPrecioXUnidad() {
        return this.precioXUnidad;
    }
    
    public void setPrecioXUnidad(BigDecimal precioXUnidad) {
        this.precioXUnidad = precioXUnidad;
    }
    public BigDecimal getStock() {
        return this.stock;
    }
    
    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }
    public BigDecimal getStockMinimo() {
        return this.stockMinimo;
    }
    
    public void setStockMinimo(BigDecimal stockMinimo) {
        this.stockMinimo = stockMinimo;
    }
    public BigDecimal getPesoEnvase() {
        return this.pesoEnvase;
    }
    
    public void setPesoEnvase(BigDecimal pesoEnvase) {
        this.pesoEnvase = pesoEnvase;
    }

    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }



}


