package Modelo;
// Generated 02/02/2018 22:50:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private String razonSocial;
     private String cuit;
     private String direccion;
     private String localidad;
     private String provincia;
     private String pais;
     private String contacto;
     private Boolean estado;
     private Set productos = new HashSet(0);
     private Set pedidos = new HashSet(0);
     private Set entradastocks = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(int idProveedor, String razonSocial, String cuit) {
        this.idProveedor = idProveedor;
        this.razonSocial = razonSocial;
        this.cuit = cuit;
    }
    public Proveedor(int idProveedor, String razonSocial, String cuit, String direccion, String localidad, String provincia, String pais, String contacto, Boolean estado, Set productos, Set pedidos, Set entradastocks) {
       this.idProveedor = idProveedor;
       this.razonSocial = razonSocial;
       this.cuit = cuit;
       this.direccion = direccion;
       this.localidad = localidad;
       this.provincia = provincia;
       this.pais = pais;
       this.contacto = contacto;
       this.estado = estado;
       this.productos = productos;
       this.pedidos = pedidos;
       this.entradastocks = entradastocks;
    }
   
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }
    public Set getEntradastocks() {
        return this.entradastocks;
    }
    
    public void setEntradastocks(Set entradastocks) {
        this.entradastocks = entradastocks;
    }




}


