package Modelo;
// Generated 02/02/2018 22:50:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private Date fechaHoraInicio;
     private Date fechaHoraFin;
     private BigDecimal montoVenta;
     private BigDecimal montoEs;
     private BigDecimal efectivoHay;
     private Set entradaSalidas = new HashSet(0);
     private Set itemVentas = new HashSet(0);

    public Turno() {
    }

	
    public Turno(int id, Usuario usuario, Date fechaHoraInicio) {
        this.id = id;
        this.usuario = usuario;
        this.fechaHoraInicio = fechaHoraInicio;
    }
    public Turno(int id, Usuario usuario, Date fechaHoraInicio, Date fechaHoraFin, BigDecimal montoVenta, BigDecimal montoEs, BigDecimal efectivoHay, Set entradaSalidas, Set itemVentas) {
       this.id = id;
       this.usuario = usuario;
       this.fechaHoraInicio = fechaHoraInicio;
       this.fechaHoraFin = fechaHoraFin;
       this.montoVenta = montoVenta;
       this.montoEs = montoEs;
       this.efectivoHay = efectivoHay;
       this.entradaSalidas = entradaSalidas;
       this.itemVentas = itemVentas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaHoraInicio() {
        return this.fechaHoraInicio;
    }
    
    public void setFechaHoraInicio(Date fechaHoraInicio) {
        this.fechaHoraInicio = fechaHoraInicio;
    }
    public Date getFechaHoraFin() {
        return this.fechaHoraFin;
    }
    
    public void setFechaHoraFin(Date fechaHoraFin) {
        this.fechaHoraFin = fechaHoraFin;
    }
    public BigDecimal getMontoVenta() {
        return this.montoVenta;
    }
    
    public void setMontoVenta(BigDecimal montoVenta) {
        this.montoVenta = montoVenta;
    }
    public BigDecimal getMontoEs() {
        return this.montoEs;
    }
    
    public void setMontoEs(BigDecimal montoEs) {
        this.montoEs = montoEs;
    }
    public BigDecimal getEfectivoHay() {
        return this.efectivoHay;
    }
    
    public void setEfectivoHay(BigDecimal efectivoHay) {
        this.efectivoHay = efectivoHay;
    }
    public Set getEntradaSalidas() {
        return this.entradaSalidas;
    }
    
    public void setEntradaSalidas(Set entradaSalidas) {
        this.entradaSalidas = entradaSalidas;
    }
    public Set getItemVentas() {
        return this.itemVentas;
    }
    
    public void setItemVentas(Set itemVentas) {
        this.itemVentas = itemVentas;
    }




}


