package Modelo;
// Generated 07/09/2017 19:19:57 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nombreUsuario;
     private int pin;

    public Usuario() {
    }

    public Usuario(int id, String nombreUsuario, int pin) {
       this.id = id;
       this.nombreUsuario = nombreUsuario;
       this.pin = pin;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public int getPin() {
        return this.pin;
    }
    
    public void setPin(int pin) {
        this.pin = pin;
    }




}


