package Modelo;
// Generated 02/02/2018 22:50:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nombreUsuario;
     private int pin;
     private Set turnos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, String nombreUsuario, int pin) {
        this.id = id;
        this.nombreUsuario = nombreUsuario;
        this.pin = pin;
    }
    public Usuario(int id, String nombreUsuario, int pin, Set turnos) {
       this.id = id;
       this.nombreUsuario = nombreUsuario;
       this.pin = pin;
       this.turnos = turnos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public int getPin() {
        return this.pin;
    }
    
    public void setPin(int pin) {
        this.pin = pin;
    }
    public Set getTurnos() {
        return this.turnos;
    }
    
    public void setTurnos(Set turnos) {
        this.turnos = turnos;
    }




}


